-- Schema SQL pour le projet "gestion_cours"
CREATE DATABASE IF NOT EXISTS gestion_cours
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_general_ci;
USE gestion_cours;

CREATE TABLE IF NOT EXISTS T_MATIERE (
  ID_MATIERE   INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  NOM_MATIERE  VARCHAR(150) NOT NULL,
  UNIQUE KEY uk_matiere_nom (NOM_MATIERE)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS T_CHAPITRE (
  ID_CHAPITRE     INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  NOM_CHAPITRE    VARCHAR(200) NOT NULL,
  CHEMIN_FICHIER  VARCHAR(255) NOT NULL,
  ID_MATIERE      INT UNSIGNED NOT NULL,
  INDEX idx_chapitre_matiere (ID_MATIERE),
  CONSTRAINT fk_chapitre_matiere
    FOREIGN KEY (ID_MATIERE) REFERENCES T_MATIERE(ID_MATIERE)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT chk_image_ext CHECK (LOWER(CHEMIN_FICHIER) REGEXP '\\.(jpe?g|png|gif|webp)$')
) ENGINE=InnoDB;
